ALTER TABLE LOGIN ADD DATA_CONFIRMACAO DATE;
ALTER TABLE LOGIN ADD CODE_CONFIRMACAO VARCHAR(5);
ALTER TABLE MEDICO_CLINICA ADD ACEITA_PARTICULAR INT(1) NOT NULL;
ALTER TABLE MEDICO DROP ACEITA_PARTICULAR;