ALTER TABLE LOGIN ADD DATA_CONFIRMACAO DATE;
ALTER TABLE LOGIN ADD CODE_CONFIRMACAO VARCHAR(5);
ALTER TABLE PROFISSIONAL ADD ACEITA_PARTICULAR INT(1) NOT NULL;
ALTER TABLE PROFISSIONAL DROP ACEITA_PARTICULAR;


ALTER TABLE PROFISSIONAL ADD CPF VARCHAR(11);
ALTER TABLE LOGIN MODIFY CODE_CONFIRMACAO VARCHAR(64);
ALTER TABLE LOGIN ADD ATIVO INT(1) NOT NULL;

ALTER TABLE PROFISSIONAL_CLINICA ADD VALOR_CONSULTA DOUBLE;

ALTER TABLE AGENDA_HORARIO ADD DIA_SEMANA INT(5);

ALTER TABLE LOGIN ADD FOTO VARCHAR(50);




INSERT INTO APP_CONFIG (CHAVE, VALOR, DATA_CRIACAO,DATA_ATUALIZACAO) VALUES ('PATH_FOTO','/var/www/agendee.com.br/f/',sysdate(),sysdate());

ALTER TABLE CONVENIO ADD ATIVO INT (1) NOT NULL;
ALTER TABLE CONVENIO_CATEGORIA ADD ATIVO INT (1) NOT NULL;
ALTER TABLE ESPECIALIDADE ADD ATIVO INT (1) NOT NULL;
UPDATE CONVENIO SET ATIVO = 1;
UPDATE CONVENIO_CATEGORIA SET ATIVO = 1;
UPDATE ESPECIALIDADE SET ATIVO = 1;


ALTER TABLE PACIENTE ADD ID_CATEGORIA INT(10);

ALTER TABLE PACIENTE ADD FOREIGN KEY (ID_CATEGORIA) REFERENCES CONVENIO_CATEGORIA(ID);






--RENOMEANDO AS TABELAS
RENAME TABLE MEDICO TO PROFISSIONAL, MEDICO_CLINICA TO PROFISSIONAL_CLINICA, MEDICO_ESPECIALIDADE TO PROFISSIONAL_ESPECIALIDADE;


ALTER TABLE PROFISSIONAL_CLINICA
DROP FOREIGN KEY PROFISSIONAL_CLINICA_ibfk_1;
ALTER TABLE PROFISSIONAL_CLINICA
CHANGE COLUMN ID_MEDICO ID_PROFISSIONAL INT(28) NOT NULL ;
ALTER TABLE PROFISSIONAL_CLINICA
ADD CONSTRAINT PROFISSIONAL_CLINICA_ibfk_1
  FOREIGN KEY (ID_PROFISSIONAL)
  REFERENCES PROFISSIONAL (ID_LOGIN)
  ON DELETE CASCADE;



ALTER TABLE PROFISSIONAL_ESPECIALIDADE 
DROP FOREIGN KEY PROFISSIONAL_ESPECIALIDADE_ibfk_1;
ALTER TABLE PROFISSIONAL_ESPECIALIDADE 
CHANGE COLUMN ID_MEDICO ID_PROFISSIONAL INT(28) NOT NULL ;
ALTER TABLE PROFISSIONAL_ESPECIALIDADE 
ADD CONSTRAINT PROFISSIONAL_ESPECIALIDADE_ibfk_1
  FOREIGN KEY (ID_PROFISSIONAL)
  REFERENCES PROFISSIONAL (ID_LOGIN)
  ON DELETE CASCADE;




ALTER TABLE AGENDA ADD ABERTURA_AGENDA INT(2) NOT NULL;
ALTER TABLE PACIENTE MODIFY TELEFONE VARCHAR(15);



ALTER TABLE LOGIN ADD KEY_DEVICE_GCM VARCHAR(255);


INSERT INTO PROFISSAO (NOME,POPULAR) VALUES ('Médico',1);
INSERT INTO PROFISSAO (NOME,POPULAR) VALUES ('Dentista',1);

ALTER TABLE ESPECIALIDADE ADD ID_PROFISSAO INT(10) NOT NULL;

UPDATE ESPECIALIDADE SET ID_PROFISSAO = 1 WHERE ID_PROFISSAO = 0;
ALTER TABLE ESPECIALIDADE ADD FOREIGN KEY (ID_PROFISSAO) REFERENCES PROFISSAO(ID);



INSERT INTO PARCEIRO_EMPRESA (NOME) VALUES ('netdente');
INSERT INTO PARCEIRO_EMPRESA (NOME) VALUES ('camtwo');
INSERT INTO PARCEIRO_EMPRESA(NOME) VALUES ('shosp');


ALTER TABLE LOGIN ADD DATA_RECUPERACAO_SENHA DATE;
ALTER TABLE  LOGIN ADD CODE_RECUPERACAO_SENHA VARCHAR(64); 

