ALTER TABLE LOGIN ADD DATA_CONFIRMACAO DATE;
ALTER TABLE LOGIN ADD CODE_CONFIRMACAO VARCHAR(5);
ALTER TABLE MEDICO_CLINICA ADD ACEITA_PARTICULAR INT(1) NOT NULL;
ALTER TABLE MEDICO DROP ACEITA_PARTICULAR;


ALTER TABLE MEDICO ADD CPF VARCHAR(11);
ALTER TABLE LOGIN MODIFY CODE_CONFIRMACAO VARCHAR(64);
ALTER TABLE LOGIN ADD ATIVO INT(1) NOT NULL;


ALTER TABLE MEDICO_CLINICA ADD VALOR_CONSULTA DOUBLE;

ALTER TABLE AGENDA_HORARIO ADD DIA_SEMANA INT(5);
